# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

@nelson = Admiral.create!(name: 'Horatio Nelson', age: 47, rank: 'Vice-Admiral of the White', killed_in_action: true)
@collingwood = Admiral.create!(name: 'Cuthbert Collingwood', age: 56, rank: 'Vice-Admiral of the Red', killed_in_action: false)
@carnegie = Admiral.create!(name: 'William Carnegie', age: 49, rank: 'Admiral of the Fleet', killed_in_action: false)
@hardgood = Admiral.create!(name: 'William Hardgood', age: 43, rank: 'Admiral of the Blue', killed_in_action: true)

@nelson.ships.create!(ship_name: 'H.M.S. Victory', guns: 104, number_of_deck: 3, sunk: false)
@nelson.ships.create!(ship_name: 'H.M.S. Africa', guns: 64, number_of_deck: 2, sunk: true)
@nelson.ships.create!(ship_name: 'H.M.S. Temeraire', guns: 98, number_of_deck: 3, sunk: true)
@nelson.ships.create!(ship_name: 'H.M.S. Neptune', guns: 98, number_of_deck: 3, sunk: false)
@nelson.ships.create!(ship_name: 'H.M.S. Leviathan', guns: 74, number_of_deck: 2, sunk: true )
@nelson.ships.create!(ship_name: 'H.M.S. Conquerer', guns: 74, number_of_deck: 2, sunk: false)
@nelson.ships.create!(ship_name: 'H.M.S. Surprise', guns: 38, number_of_deck: 2, sunk: false)
@nelson.ships.create!(ship_name: 'H.M.S. Leopard', guns: 50, number_of_deck: 2, sunk: true)
@carnegie.ships.create!(ship_name: 'H.M.S. Britannia', guns: 100, number_of_deck: 3, sunk: true )
@carnegie.ships.create!(ship_name: 'H.M.S. Agamemnon', guns: 64, number_of_deck: 2, sunk: false)
@carnegie.ships.create!(ship_name: 'H.M.S. Ajax', guns: 74, number_of_deck: 2, sunk: false)
@carnegie.ships.create!(ship_name: 'H.M.S. Orion', guns: 74, number_of_deck: 2, sunk: true)
@carnegie.ships.create!(ship_name: 'H.M.S. Minotaur', guns: 74, number_of_deck: 2, sunk: false)
@carnegie.ships.create!(ship_name: 'H.M.S. Spartiate', guns: 74, number_of_deck: 2, sunk: false)
@collingwood.ships.create!(ship_name: 'H.M.S. Royal Sovereign', guns: 100, number_of_deck: 3, sunk: true)
@collingwood.ships.create!(ship_name: 'H.M.S. Belleisle', guns: 74, number_of_deck: 2, sunk: false)
@collingwood.ships.create!(ship_name: 'H.M.S. Mars', guns: 74, number_of_deck: 2, sunk: true)
@collingwood.ships.create!(ship_name: 'H.M.S. Tonnant', guns: 80, number_of_deck: 2, sunk: false)
@collingwood.ships.create!(ship_name: 'H.M.S. Bellerophon', guns: 74, number_of_deck: 2, sunk: true)
@collingwood.ships.create!(ship_name: 'H.M.S. Colossus', guns: 74, number_of_deck: 2, sunk: true)
@collingwood.ships.create!(ship_name: 'H.M.S. Achille', guns: 74, number_of_deck: 2, sunk: false)
@collingwood.ships.create!(ship_name: 'H.M.S. Revenge', guns: 74, number_of_deck: 2, sunk: true)
@hardgood.ships.create!(ship_name: 'H.M.S. Polyphemus', guns: 64, number_of_deck: 2, sunk: false)
@hardgood.ships.create!(ship_name: 'H.M.S. Swiftsure', guns: 74, number_of_deck: 2, sunk: true)
@hardgood.ships.create!(ship_name: 'H.M.S. Dreadnought', guns: 98, number_of_deck: 3, sunk: false)
@hardgood.ships.create!(ship_name: 'H.M.S. Defiance', guns: 74, number_of_deck: 2, sunk: false)
@hardgood.ships.create!(ship_name: 'H.M.S. Thunderer', guns: 74, number_of_deck: 2, sunk: true)
@hardgood.ships.create!(ship_name: 'H.M.S. Defence', guns: 74, number_of_deck: 2, sunk: false)
